version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=123698741
        - MYSQL_DATABASE=test
    ports:
    - 3306:3306

    expose:
    - 3306

  app:
    build: .
    restart: always
    ports: 
      - 3000:3000
    depends_on:
      - mysql