version: "3"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123698741
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306

    expose:
      - 3306

  app1:
    build: .
    restart: always
    ports:
      - 3000:3001
    depends_on:
      - mysql

  app2:
    build: .
    restart: always
    ports:
      - 3000:3002
    depends_on:
      - mysql

  app3:
    build: .
    restart: always
    ports:
      - 3000:3003
    depends_on:
      - mysql

  app4:
    build: .
    restart: always
    ports:
      - 3000:3004
    depends_on:
      - mysql

  app5:
    build: .
    restart: always
    ports:
      - 3000:3005
    depends_on:
      - mysql
